// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4V8nkXTZR_WSr5he-PXuIREfX-PKzT_M',
    appId: '1:26446748418:web:eefb34d9ba6df3d026401b',
    messagingSenderId: '26446748418',
    projectId: 'attendance-practice-b15c5',
    authDomain: 'attendance-practice-b15c5.firebaseapp.com',
    storageBucket: 'attendance-practice-b15c5.firebasestorage.app',
    measurementId: 'G-FMFEHXL023',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUJpKH-TYpxzNNFYJtbNFHb9slMtv6C4',
    appId: '1:26446748418:android:6b65aa4ac62220f326401b',
    messagingSenderId: '26446748418',
    projectId: 'attendance-practice-b15c5',
    storageBucket: 'attendance-practice-b15c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-RWV-w7pLbuo1_DdJib38sFnawnvcVA0',
    appId: '1:26446748418:ios:9ff42c5c9ad5933926401b',
    messagingSenderId: '26446748418',
    projectId: 'attendance-practice-b15c5',
    storageBucket: 'attendance-practice-b15c5.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-RWV-w7pLbuo1_DdJib38sFnawnvcVA0',
    appId: '1:26446748418:ios:9ff42c5c9ad5933926401b',
    messagingSenderId: '26446748418',
    projectId: 'attendance-practice-b15c5',
    storageBucket: 'attendance-practice-b15c5.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4V8nkXTZR_WSr5he-PXuIREfX-PKzT_M',
    appId: '1:26446748418:web:257eb0dbb7f1c55026401b',
    messagingSenderId: '26446748418',
    projectId: 'attendance-practice-b15c5',
    authDomain: 'attendance-practice-b15c5.firebaseapp.com',
    storageBucket: 'attendance-practice-b15c5.firebasestorage.app',
    measurementId: 'G-MM9DBXH3TS',
  );

}